replicaCount: 1
# 
# Nested Struncture (enabling nested override for efficient provisioning); 
# i.e, {{ aaa. bbb }} = value is the following 
# aaa:
#    bbb: value


image:
  name: loggen
  repository: datapull
  tag: latest
  pullPolicy: IfNotPresent

container:
  name: loggen
  port: 8066


service:
  name: loggen
  port: 8066
  replicas: 1
  portName: http
  endPoint: /metrics



# Frequency of Prom polling and scrapping metrics
endpoints:
  scrape: 10s